train_cols = ['age', 'worker_class', 'industry_code', 'occupation_code', 'education',
       'wage_per_hour', 'enroll_edu_last_wk', 'marital_status',
       'major_industry_code', 'major_occupation_code', 'race',
       'hispanic_origin', 'sex', 'labor_union_member', 'unemployment_reason',
       'employment_status', 'capital_gains', 'capital_losses',
       'stock_dividends', 'tax_filer_status', 'previous_residence_region',
       'previous_residence_state', 'household_status', 'household_summary',
       'instance_weight', 'migration_code_change_in_msa',
       'migration_code_change_in_reg', 'migration_code_move_within_reg',
       'live_in_this_house_1_year_ago', 'migration_prev_res_in_sunbelt',
       'num_persons_worked_for_employer', 'family_members_under_18',
       'birth_country_father', 'birth_country_mother', 'birth_country',
       'citizenship', 'self_employed', 'veteran_questionnaire',
       'veteran_benfits', 'weeks_worked_in_year', 'year', 'income']

test_cols = train_cols[:-1]


education_dict = {'Children':0,'Less than 1st grade':1,'1st 2nd 3rd or 4th grade':1,'5th or 6th grade':2,'7th and 8th grade':2,
                  '9th grade':2,'10th grade':3,'11th grade':3,'12th grade no diploma':3,'High school graduate':4,
                  'Some college but no degree':4, 'Associates degree-occup /vocational':5,'Associates degree-academic program':5,
                  'Bachelors degree(BA AB BS)':6, 'Masters degree(MA MS MEng MEd MSW MBA)':7,'Prof school degree (MD DDS DVM LLB JD)':8,'Doctorate degree(PhD EdD)':8}

other_cols = ['migration_code_change_in_msa', 'migration_code_change_in_reg', 
              'migration_code_move_within_reg', 'migration_prev_res_in_sunbelt']

test_data_point = [{
	"age": 47,
	"worker_class": " Self-employed-not incorporated",
	"industry_code": 4,
	"occupation_code": 34,
	"education": " High school graduate",
	"wage_per_hour": 0,
	"enroll_edu_last_wk": " Not in universe",
	"marital_status": " Married-civilian spouse present",
	"major_industry_code": " Construction",
	"major_occupation_code": " Precision production craft & repair",
	"race": " White",
	"hispanic_origin": " All other",
	"sex": " Male",
	"labor_union_member": " Not in universe",
	"unemployment_reason": " Not in universe",
	"employment_status": " Full-time schedules",
	"capital_gains": 7298,
	"capital_losses": 0,
	"stock_dividends": 0,
	"tax_filer_status": " Joint both under 65",
	"previous_residence_region": " Not in universe",
	"previous_residence_state": " Not in universe",
	"household_status": " Householder",
	"household_summary": " Householder",
	"instance_weight": 1038.34,
	"migration_code_change_in_msa": " ?",
	"migration_code_change_in_reg": " ?",
	"migration_code_move_within_reg": " ?",
	"live_in_this_house_1_year_ago": " Not in universe under 1 year old",
	"migration_prev_res_in_sunbelt": " ?",
	"num_persons_worked_for_employer": 1,
	"family_members_under_18": " Not in universe",
	"birth_country_father": " ?",
	"birth_country_mother": " ?",
	"birth_country": " ?",
	"citizenship": " Foreign born- U S citizen by naturalization",
	"self_employed": 1,
	"veteran_questionnaire": " Not in universe",
	"veteran_benfits": 2,
	"weeks_worked_in_year": 52,
	"year": 95
}]